;e2 -360
;e3 -880
{units
	(define "charge_level_1_heavy"
		{charge 1} {fore -120}
	)
	(define "charge_level_2_heavy"
		{charge 1} {fore -180}
	)
	(define "charge_level_3_light"
		{charge 1} {fore -300}
	)
	(define "charge_level_3"
		{charge 1} {fore -360}
	)
	(define "charge_level_3_heavy"
		{charge 1} {fore -420}
	)	
	(define "charge_level_4_light"
		{charge 1} {fore -420}
	)	
	(define "charge_level_4"
		{charge 1} {fore -480}
	)
	(define "charge_level_4_heavy"
		{charge 1} {fore -540}
	)
	(define "charge_level_5_light"
		{charge 1} {fore -820}
	)	
	(define "charge_level_5"
		{charge 1} {fore -880}
	)
	(define "charge_level_5_heavy"
		{charge 1} {fore -940}
	)
	(define "charge_level_6_light"
		{charge 1} {fore -940}
	)	
	(define "charge_level_6"
		{charge 1} {fore -1000}
	)
	(define "charge_level_6_heavy"
		{charge 1} {fore -1060}
	)
;Units
;[Zenite_Gun]______________________________________________________________________________________________________________________________________________________________
;level_4
	{"flak18"						("charge_level_4")}
	{"flak18_stan"					("charge_level_4")}	
	{"flak18_trailer(ger)"			("charge_level_4")}	
	{"52k"							("charge_level_4")}
	{"52k_trailer(rus)"				("charge_level_4")}	
	;level_5
	{"m2cannon90mm"					("charge_level_5")}
	{"m2cannon90mm_trailer(usa)"	("charge_level_5")}	
;[AT_Cannon]________________________________________________________________________________________________________________________________________________________________
;level_4
	{"pak40"						("charge_level_4")}
	{"pak40_trailer(ger)"			("charge_level_4")}	
	{"sk18"							("charge_level_4")}
	{"sk18_trailer(ger)"			("charge_level_4")}	
	{"zis2"							("charge_level_4")}
	{"zis2_trailer(rus)"			("charge_level_4")}	
	{"m5"							("charge_level_4")}
	{"m5_trailer(usa)"				("charge_level_4")}	
	;level_5
	{"pak43"						("charge_level_5")}
	{"pak43_trailer(ger)"			("charge_level_5")}	
	{"bs3"							("charge_level_5")}
	{"bs3_trailer(rus)"				("charge_level_5")}	
;[Howitzer]_________________________________________________________________________________________________________________________________________________________________
;level_1
	{"m8_howitzer"					("charge_level_1_heavy")}
	{"m8_howitzer_trailer(usa)"		("charge_level_1_heavy")}	
;level_2
	{"lefh18"						("charge_level_2_heavy")}
	{"lefh18_trailer(ger)"			("charge_level_2_heavy")}	
	{"m30"							("charge_level_2_heavy")}
	{"m30_trailer(rus)"				("charge_level_2_heavy")}	
	{"m2a1l"						("charge_level_2_heavy")}
	{"m2a1l_trailer(usa)"			("charge_level_2_heavy")}	
;level_5
	{"mrs18"						("charge_level_5")}
	{"mrs18_trailer(ger)"			("charge_level_5")}	
	{"203b4"						("charge_level_5")}
	{"203b4_trailer(rus)"			("charge_level_5")}	
	{"203_m1"						("charge_level_5")}	
	{"203_m1_trailer(usa)"			("charge_level_5")}		
;[Rocket_Launcher_Stan]_____________________________________________________________________________________________________________________________________________________
;level_4
	{"nebelwerfer41"				("charge_level_4")}
	{"nebelwerfer41_trailer(ger)"	("charge_level_4")}	
;level_5
	{"nebelwerfer42"	("charge_level_5")}	
	{"nebelwerfer42_trailer(ger)"	("charge_level_5")}	
;[Rocket_Launcher_Vehicle]_____________________________________________________________________________________________________________________________________________________
;level_5
	{"bm13"				("charge_level_5_heavy")}	
;level_6
	{"sdkfz4"			("charge_level_6_heavy")}	
	{"m4a3c"			("charge_level_6_heavy")}
;[Car]_____________________________________________________________________________________________________________________________________________________________________
;level_4
;level_4
	{"dodgewc51_m2hb"	("charge_level_4_light")}	
;[APC]_____________________________________________________________________________________________________________________________________________________________________
;level_4
	{"sdkfz234"					("charge_level_4_light")}
	{"m3_scout_rus"				("charge_level_4_light")}
	{"m3_scout"					("charge_level_4_light")}
;level_5
	{"sdkfz251_16"				("charge_level_5_light")}
	{"m3_g"						("charge_level_5_light")}
	{"m3_ally_g"				("charge_level_5_light")}
	{"sdkfz251d"				("charge_level_5_light")}
;level_5
	{"pz4f2_inf"				("charge_level_6_light")}
	{"pz4g_inf"					("charge_level_6_light")}
	{"t34_76_inf"				("charge_level_6_light")}
	{"t34_2_inf"				("charge_level_6_light")}
	{"m4a1_inf"					("charge_level_6_light")}
	{"m4a3dd_inf"				("charge_level_6_light")}
;[Zenite_Vehicle]___________________________________________________________________________________________________________________________________________________________
;level_4
	{"29k"				("charge_level_4")}
	{"welberwind"		("charge_level_4")}
	{"m19"				("charge_level_4")}
;[Minetral]______________________________________________________________________________________________________________________________________________________________
;level_6
	{"t34m"				("charge_level_6_light")}
	{"m4a3m"			("charge_level_6_light")}
;[Tank Medium]______________________________________________________________________________________________________________________________________________________________
;level_1
	{"m2a1_med"			("charge_level_1_heavy")}
;level_2
	{"pz3f"				("charge_level_2_heavy")}
	{"pz3f_rus"			("charge_level_2_heavy")}
	{"t28"				("charge_level_2_heavy")}
	{"valentine_rus"	("charge_level_2_heavy")}
	{"mk2a"				("charge_level_2_heavy")}
	{"chi-he"			("charge_level_2_heavy")}
;level_4
	{"pz4d"				("charge_level_4")}
	{"pz4g"				("charge_level_4")}
	{"pz4h"				("charge_level_4")}
	{"t34_2"			("charge_level_4")}
	{"t34_armored"		("charge_level_4")}
	{"t34_76_41"		("charge_level_4")}
	{"m4a2_rus"			("charge_level_4")}
	{"t34_1"			("charge_level_4")}
	{"t34_57_43"		("charge_level_4")}
	{"m4a1_eng"			("charge_level_4")}
	{"m4a2"				("charge_level_4")}
	{"m4a3_75"			("charge_level_4")}
	{"m4a4"				("charge_level_4")}
	{"m4a3dd"			("charge_level_4")}
	{"m4a3_105"			("charge_level_4")}
	{"chi-to"			("charge_level_4")}
;level_5
	{"pz5a"				("charge_level_5")}
	{"pz5a_po"			("charge_level_5")}
	{"t34_3"			("charge_level_5")}
	{"ot34_76_42"		("charge_level_5")}
	{"t34_85"			("charge_level_5")}
	{"t34_85_po"		("charge_level_5")}
	{"m4a2_76w_rus"		("charge_level_5")}
	{"m4a3e8"			("charge_level_5")}
	{"m4a3e8_po"		("charge_level_5")}
	{"m4a2_76w"			("charge_level_5")}
	{"m4a2_76w_thunderbolt"		("charge_level_5")}
	{"m4a3vc"			("charge_level_5")}
	{"m4a3e2"			("charge_level_5")}
	{"m4a3_zippo"		("charge_level_5")}
;level_6
	{"pz5g"				("charge_level_5")}
	{"t34_85m"			("charge_level_5")}
	{"t34_85m_po"		("charge_level_5")}
	{"m4a3e2_jumbo_76"	("charge_level_5")}
;[Tank Heavy]_______________________________________________________________________________________________________________________________________________________________
;level_1
;level_2
	{"t35"				("charge_level_2_heavy")}
	{"pzb2740f"			("charge_level_2_heavy")}
;level_3
	{"kv1"				("charge_level_3_heavy")}
	{"kv1_za_rodinu"	("charge_level_3_heavy")}
	{"mk4_rus"			("charge_level_3_heavy")}
	{"mk4"				("charge_level_3_heavy")}
;level_4
	{"pz6h"				("charge_level_4_heavy")}
	{"kv1e"				("charge_level_4_heavy")}
	{"kv2"				("charge_level_4_heavy")}
	{"kv1s"				("charge_level_4_heavy")}
	{"kv85"				("charge_level_4_heavy")}
	{"kv1_zis5"			("charge_level_4_heavy")}
;level_5
	{"pz6e"				("charge_level_5_heavy")}
	{"kv8"				("charge_level_5_heavy")}
	{"m26"				("charge_level_5_heavy")}
	{"is1"				("charge_level_5_heavy")}
	{"centurion"		("charge_level_5_heavy")}
	{"chi-ri"			("charge_level_5_heavy")}
;level_6
	{"pz6b"				("charge_level_6_heavy")}
	{"pz6bh"			("charge_level_6_heavy")}
	{"is2_44"			("charge_level_6_heavy")}
	{"is2_early"		("charge_level_6_heavy")}
	{"is2"				("charge_level_6_heavy")}
	{"is3"				("charge_level_6_heavy")}
	{"t29"				("charge_level_6_heavy")}
	{"m26e4"			("charge_level_6_heavy")}
;[SPG]______________________________________________________________________________________________________________________________________________________________________
;level_4
	{"stuh42"			("charge_level_4")}
	{"su122"			("charge_level_4")}
	{"m7"				("charge_level_4_light")}
	{"sturmpz1"			("charge_level_4_light")}
;level_5
	{"brumbar"			("charge_level_5")}
	{"hummel"			("charge_level_5_light")}
	{"m12gmc"			("charge_level_5_light")}
	{"su152"			("charge_level_5")}	
;level_6
	{"sturmtiger"		("charge_level_6_heavy")}
	{"karlthor"			("charge_level_6_heavy")}
;[Tank_Hunter]______________________________________________________________________________________________________________________________________________________________________
;level_4
	{"hetzer"			("charge_level_4_light")}
	{"stug3g"			("charge_level_4")}
	{"jagdpanzer"		("charge_level_4")}
	{"stug3f"			("charge_level_4")}
	{"sdkfz251_22"		("charge_level_4_light")}
	{"su85"				("charge_level_4")}
	{"m18"				("charge_level_4_light")}
	{"m10wolverine"		("charge_level_4")}
;level_5
	{"stug4g"			("charge_level_5")}
	{"nashorn"			("charge_level_5_light")}
	{"jagdpanzer_iv"	("charge_level_5")}
	{"jagdpanzer_iv_wacher"	("charge_level_5")}
	{"su100"			("charge_level_5")}
	{"m36"				("charge_level_5")}
;level_6
	{"elefant"			("charge_level_6_heavy")}
	{"ferdinand"		("charge_level_6_heavy")}
	{"jagdpanther"		("charge_level_6")}
	{"jagdtiger"		("charge_level_6_heavy")}
	{"isu122"			("charge_level_6_heavy")}
	{"isu152"			("charge_level_6_heavy")}
	{"t95"				("charge_level_6_heavy")}	
}