(include "generic.inc")
(include "soldiers.inc")

;assault_soldier
("breeds_g_r_u"						name(assault_commander)				sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(light_assault_commander)		sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(heavy_assault_commander)		sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(assault_rifle_rookie)			sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(light_assault_rifle_rookie)	sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(heavy_assault_rifle)			sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(assault_smg_rookie)			sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(light_assault_smg_rookie)		sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(heavy_assault_smg)				sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(assault_mgun)					sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(heavy_assault_mgun)			sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(assault_at_rifle)				sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(heavy_assault_bazooker)		sc(0.5)		cp(0.35)	cw(s4))
("breed_u"							name(light_assault_commander_fra)   sc(0.5)		cp(0.35)	cw(s4))
("breed_u"							name(light_assault_rifle_rookie_fra)   sc(0.5)		cp(0.35)	cw(s4))
("breed_u"							name(light_assault_smg_rookie_fra)     sc(0.5)		cp(0.35)	cw(s4))

;apc_troopers
("breed_auto_g"						name(apc_opel_blitz_mgun_commander)	sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_opel_blitz_mgun_rifle)		sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_opel_blitz_mgun_smg)		sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_opel_blitz_commander)		sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_opel_blitz_rifle)			sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_opel_blitz_smg)			sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_251_1_commander)			sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_251_1_rifle)				sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_251_1_smg)					sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_251_10_commander)			sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_251_10_rifle)				sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(apc_251_10_smg)				sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_r"						name(apc_gaz_aa_commander)			sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_r"						name(apc_gaz_aa_rifle)				sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_r"						name(apc_gaz_aa_smg)				sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(apc_m3a1_commander)			sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(apc_m3a1_rifle)				sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(apc_m3a1_smg)					sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(apc_m3a2_commander)			sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(apc_m3a2_rifle)				sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(apc_m3a2_smg)					sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(apc_t20_commander)				sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(apc_t20_rifle)					sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(apc_t20_smg)					sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_u"						name(apc_gmc_commander)				sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_u"						name(apc_gmc_rifle)					sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_u"						name(apc_gmc_smg)					sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_u"						name(apc_uc_commander)				sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_u"						name(apc_uc_rifle)					sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_u"						name(apc_uc_smg)					sc(0.5)		cp(0.35)	cw(s4))

;tank_troopers
("breed_auto_g"						name(apc_pz4f2_commander)			sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(apc_pz4f2_rifle) 				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(apc_pz4f2_smg) 				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(apc_pz4g_grenadier)			sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_r"						name(apc_t34_76_commander)			sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_r"						name(apc_t34_76_rifle)				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_r"						name(apc_t34_76_smg) 				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_r"						name(apc_t34_2_sturmovik) 			sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_u"						name(apc_m4a1_commander)			sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_u"						name(apc_m4a1_rifle) 				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_u"						name(apc_m4a1_smg) 					sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_u"						name(apc_m4a3dd_marine) 			sc(0.5)		cp(0.35)	cw(s5)))

("breeds_spe_g_r_u_e_j"				name(tankman)						sc(0.5)		cp(0)	cw(s0))
("breed_auto_g"						name(tankman_officer) 				sc(0.5)		cp(0)	cw(s0))

;miner
("breeds_withdrawn_g_r_u"			name(antipersonel_miner)			sc(0.5)		cp(0)	cw(s0))
("breeds_withdrawn_g_r_u"			name(antitank_miner)				sc(0.5)		cp(0)	cw(s0))
("breeds_withdrawn_g_r_u"			name(universal_miner)				sc(0.5)		cp(0)	cw(s0))

;artilleryman
("breeds_spe_g_r_u_e_j"				name(artilleryman)					sc(0.5)		cp(0)	cw(s0))
("breed_spe_g"						name(artilleryman_paratrooper)		sc(0.5)		cp(0)	cw(s0))


("breeds_spe_g_r_u"					name(pilot)							sc(0.5)		cp(0)	cw(s0))

("breeds_spe_g_r_u"					name(creep)							sc(0.5)		cp(0)	cw(s4))

("breeds_spe_g_r_u"					name(artilleryman_veh)				sc(0.5)		cp(0)	cw(s4))

;at_rifle
("breeds_g_r_u"						name(at_rifle)						sc(0.5)		cp(0.35)	cw(s4))
("breed_r"							name(at_rifle_ptrs)					sc(0.5)		cp(0.35)	cw(s4))
("breed_g"							name(at_rifle_solothurn)			sc(0.5)		cp(0.35)	cw(s4))

;rifle_grenadiers
("breed_r"							name(rifle_grenadier)				sc(0.5)		cp(0.35)	cw(s4))

;at_squad
("breed_g"							name(rifle_panzerfaust)				sc(0.5)		cp(0.35)	cw(s4))
("breed_r"							name(bottle_thrower)				sc(0.5)		cp(0.35)	cw(s4))

("breeds_r_u"						name(bomberman)						sc(0.5)		cp(0.35)	cw(s4))

("breeds_g_r_u"						name(bazooker)						sc(0.5)		cp(0.35)	cw(s4))
("breed_u"							name(bazooker_m18)					sc(0.5)		cp(0.35)	cw(s4))

;edelweiss
("breed_auto_g"						name(edelweiss)						sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(edelweiss_g43)					sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(edelweiss_fg42)				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(edelweiss_mgun)				sc(0.5)		cp(0.35)	cw(s5))

("breed_auto_g"						name(grenadier)						sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(grenadier_mgun)				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(grenadier_pfaust)				sc(0.5)		cp(0.35)	cw(s5))

("breed_auto_r"						name(marine_avs)					sc(0.5)		cp(0.35)	cw(s5))

("breeds_auto_r_u"					name(marine)						sc(0.5)		cp(0.35)	cw(s5))
("breeds_auto_r_u"					name(marine_mgun)					sc(0.5)		cp(0.35)	cw(s5))

("breed_auto_u"						name(marine_bar)					sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_u"						name(marine_radioman)				sc(0.5)		cp(0.35)	cw(s5))

("breeds_withdrawn_sale_spe_g_r_u"	name(engineer)						sc(0.5)		cp(0)	    cw(s0))

("breeds_spe_corpsman_g_r_u"		name(flamer)						sc(0.5)		cp(0.35)	cw(s4))

;mgun
("breeds_auto_g_r_u"				name(mgun)							sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(mgun_late)						sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(mgun_late)						sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(mgun_mg26)						sc(0.5)		cp(0.35)	cw(s4))

("breeds_auto_g_r_u"				name(mgun_supporter)				sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(mgun_supporter_late)			sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(mgun_supporter_late)			sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(mgun_supporter_mg26)			sc(0.5)		cp(0.35)	cw(s4))

("breed_auto_g"						name(storm_commander)				sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_g_r_u"				name(mgun_commander)				sc(0.5)		cp(0.35)	cw(s4))

("breed_auto_g"						name(mgun_commander_late)			sc(0.5)		cp(0.35)	cw(s4))
("breeds_auto_r_u"					name(mgun_commander_late)			sc(0.5)		cp(0.35)	cw(s4))
("breed_auto_g"						name(mgun_commander_mg26)			sc(0.5)		cp(0.35)	cw(s4))


("breeds_auto_cw_g_r_u"				name(paratrooper)					sc(0.5)		cp(0.35)	cw(sp))
("breeds_auto_cw_g_r_u"				name(paratrooper_mgun)				sc(0.5)		cp(0.35)	cw(sp))

("breed_auto_cw_u"					name(paratrooper_elite)				sc(0.5)		cp(0.35)	cw(sp))
("breed_auto_cw_u"					name(paratrooper_elite_smg)			sc(0.5)		cp(0.35)	cw(sp))
("breed_auto_cw_u"					name(paratrooper_elite_mgun)		sc(0.5)		cp(0.35)	cw(sp))

;rifle
("breed_g"							name(storm_rifle)					sc(0.5)		cp(0.35)	cw(s6))
("breeds_g_r_u"						name(rifle)							sc(0.5)		cp(0.35)	cw(s6))
("breeds_g_r_u"						name(rifle_rookie)					sc(0.5)		cp(0.35)	cw(s6))
("breeds_g_r_u"						name(rifle_veteran)					sc(0.5)		cp(0.35)	cw(s6))
("breed_r"							name(rifle_reserv)					sc(0.5)		cp(0.35)	cw(s6))

;special infantry
("breeds_auto_spe_g_r_u"			name(saboteur)						sc(0.5)		cp(0.35)	cw(s0))
("breeds_auto_spe_g_r_u"			name(saboteur_smg)					sc(0.5)		cp(0.35)	cw(s0))
("breeds_auto_spe_g_r_u"			name(saboteur_sniper)				sc(0.5)		cp(0.35)	cw(s0))

("breeds_auto_spe_g_r_u_e_j"		name(arty_spotter)					sc(0.5)		cp(0.35)	cw(s0))

("breeds_g_r_u"						name(officer)						sc(0.5)		cp(0.35)	cw(officer))
("breeds_spe_g_r_u"					name(scout)							sc(0.5)		cp(0.35)	cw(s0))
("breeds_spe_g_r_u"					name(apc_m3scout_scout)				sc(0.5)		cp(0.35)	cw(s0))
("breeds_spe_g_r_u"					name(apc_m3scout_gunner)			sc(0.5)		cp(0.35)	cw(s0))
("breeds_spe_g_r_u"					name(apc_m3scout_driver)			sc(0.5)		cp(0.35)	cw(s0))

;support
("breeds_g_r_u"						name(saper)							sc(0.5)		cp(0.35)	cw(s0))

("breeds_g_r_u"						name(saper_veteran)					sc(0.5)		cp(0.35)	cw(s0))

("breed_g"							name(sturmpioneer_commander)		sc(0.5)		cp(0.35)	cw(s6))
("breed_g"							name(sturmpioneer_flamer)			sc(0.5)		cp(0.35)	cw(s0))
("breed_g"							name(sturmpioneer_saper)			sc(0.5)		cp(0.35)	cw(s0))
("breed_g"							name(sturmpioneer_mgun)				sc(0.5)		cp(0.35)	cw(s0))
("breed_g"							name(sturmpioneer_radioman)			sc(0.5)		cp(0.35)	cw(s0))

("breeds_withdrawn_sale_corpsman_g_r_u"	name(corpsman)					sc(0.5)		cp(0)	    cw(s0))
("breeds_g_r_u"						name(combat_medic)					sc(0.5)		cp(0.35)	cw(s0))

;smg
("breed_g"							name(storm_smg)						sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(smg)							sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(smg_rookie)					sc(0.5)		cp(0.35)	cw(s4))
("breed_r"							name(smg_rookie_ppd)				sc(0.5)		cp(0.35)	cw(s4))
("breeds_g_r_u"						name(smg_veteran)					sc(0.5)		cp(0.35)	cw(s4))

("breeds_spe_g_r_u"					name(sniper)						sc(0.5)		cp(0.35)	cw(s0))
("breed_spe_g"						name(jaeger_sniper)					sc(0.5)		cp(0.35)	cw(s0))
("breeds_spe_g_r_u"					name(sniper_elite)					sc(0.5)		cp(0.35)	cw(s0))

("breed_auto_g"						name(ss)							sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(ss_faust)						sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(ss_mgun)						sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_g"						name(ss_driver)						sc(0.5)		cp(0.35)	cw(s5));ss_rifle	; не учитывается в бре отряда
("breed_auto_g"						name(ss_rifle)						sc(0.5)		cp(0.35)	cw(s5));ss_rifle	; не учитывается в бре отряда


("breed_auto_r"						name(sturmovik)						sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_spe_r"					name(sturmovik_flame)				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_r"						name(sturmovik_mgun)				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_r"						name(sturmovik_atr)					sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_r"						name(sturmovik_rifle)				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_u"						name(ranger)						sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_u"						name(ranger_shotgun)				sc(0.5)		cp(0.35)	cw(s5))
("breed_auto_u"						name(ranger_mgun)					sc(0.5)		cp(0.35)	cw(s5))

("breeds_g_r_u"						name(hunter)						sc(0.5)		cp(0.35)	cw(s0))

("breed_u"							name(mp)							sc(0.5)		cp(0.35)	cw(s0))
("breed_u"							name(mp_driver)						sc(0.5)	    cp(0)	    cw(s0))
("breed_u"							name(mp_gunner)						sc(0.5)	    cp(0)	    cw(s0))
("breed_u"							name(mp_veteran)					sc(0.5)		cp(0.35)	cw(s0))

;hunter_ai
("breeds_g_r_u"						name(hunter_ai)						sc(0.5)		cp(0.35)	cw(s7))
("breeds_g_r_u"						name(hunter_ai_commander)			sc(0.5)		cp(0.35)	cw(s7))
("breeds_g_r_u"						name(hunter_ai_overwatch)			sc(0.5)		cp(0.35)	cw(s7))

("breed_g"							name(ur_squad_at_rifle)				sc(0.5)		cp(0.35)	cw(s4))
("breed_g"							name(ur_squad_commander)			sc(0.5)		cp(0.35)	cw(s4))
("breed_g"							name(ur_squad_saper)				sc(0.5)		cp(0.35)	cw(s4))
("breed_g"							name(ur_squad_supporter)			sc(0.5)		cp(0.35)	cw(s4))

("breed_auto_g"						name(brandenburger_commander)		sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_g"						name(brandenburger_driver)			sc(0.5)		cp(0)	    cw(s0));premium_squad_free	; не учитывается в бре отряда
("breed_auto_g"						name(brandenburger_sniper)			sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_g"						name(brandenburger_rifle)			sc(0.5)		cp(0)	    cw(s0));premium_squad_free	; не учитывается в бре отряда
("breed_auto_g"						name(brandenburger_smg)				sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_g"						name(brandenburger_radioman)		sc(0.5)		cp(0.35)	cw(s0))

("breed_auto_r"						name(nkvd_commander)				sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_r"						name(nkvd_rifle)					sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_r"						name(nkvd_smg)						sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_r"						name(nkvd_mgun)						sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_r"						name(nkvd_sniper)					sc(0.5)		cp(0.35)	cw(s0))

("breed_auto_u"						name(devil_mgun)					sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_u"						name(devil_rifle)					sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_u"						name(devil_sniper)					sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_u"						name(devil_bazooker)				sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_u"						name(devil_commander)				sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_u"						name(devil_saboteur)				sc(0.5)		cp(0.35)	cw(s0))
("breed_auto_u"						name(devil_driver)					sc(0.5)	    cp(0)	    cw(s0))

("breed_g"							name(patrol_commander)				sc(0.5)		cp(0.35)	cw(s6))
("breed_g"							name(patrol_saper)					sc(0.5)		cp(0.35)	cw(s0))
("breed_g"							name(patrol_mgun)					sc(0.5)		cp(0.35)	cw(s0))
("breed_g"							name(patrol_smg)					sc(0.5)		cp(0.35)	cw(s0))
("breed_g"							name(patrol_smg2)					sc(0.5)		cp(0.35)	cw(s0))

;elite_apc_infantry
("breed_auto_u"						name(guard_bazooker)			sc(0.5)		cp(0.35) cw(s4))
("breed_auto_u"						name(guard_commander)			sc(0.5)		cp(0.35) cw(s4))
("breed_auto_u"						name(guard_driver)				sc(0.5)		cp(0) cw(s4))
("breed_auto_u"						name(guard_gunner)				sc(0.5)		cp(0) cw(s4))
("breed_auto_u"						name(guard_mgun)				sc(0.5)		cp(0.35) cw(s4))
("breed_auto_u"						name(guard_rifle)				sc(0.5)		cp(0.35) cw(s4))

("breed_auto_r"						name(guard_commander)			sc(0.5)		cp(0.35) cw(s5))
("breed_auto_r"						name(guard_driver)				sc(0.5)		cp(0)    cw(s5))
("breed_auto_r"						name(guard_gunner)				sc(0.5)		cp(0)    cw(s5))
("breed_auto_r"						name(guard_mgun)				sc(0.5)		cp(0.35) cw(s5))
("breed_auto_r"						name(guard_rifle)				sc(0.5)		cp(0.35) cw(s5))
("breed_auto_r"						name(guard_smg)					sc(0.5)		cp(0.35) cw(s5))
("breed_auto_r"						name(guard_sniper)				sc(0.5)		cp(0.35) cw(s5))

;---------------------------SPECIAL-----------------------------
("hero_r"							name(saboteur_rus_hero)				sc(0.5)	cp(0)	cw(s0))
("narrator_r"						name(correspondent_rizin)			sc(0.5)	cp(0)	cw(s0))

("dusty_faces_g"					name(degen)							sc(0.5)		cp(0.35)	cw(s4)))
("dusty_faces_g"					name(feldmann)						sc(0.5)		cp(0.35)	cw(s4)))
("dusty_faces_g"					name(freischmidt)					sc(0.5)		cp(0.35)	cw(s4)))
("dusty_faces_g"					name(fuchs)							sc(0.5)		cp(0.35)	cw(s4)))
("dusty_faces_g"					name(ilgen)							sc(0.5)		cp(0.35)	cw(s4)))
("dusty_faces_g"					name(jansen)						sc(0.5)		cp(0.35)	cw(s4)))
("dusty_faces_g"					name(kowalski)						sc(0.5)		cp(0.35)	cw(s4)))
("dusty_faces_g"					name(kruger)						sc(0.5)		cp(0.35)	cw(s4)))
("dusty_faces_g"					name(lischewski)					sc(0.5)		cp(0.35)	cw(s4)))