{difficulty
	{tags "single" "cooperative" "raid" "coop_mission" "skirmish" "groundcontrol" "groundcontrol_no_script" "groundcontrol_deathmatch" "groundcontrol_invasion" "groundcontrol_bases" "combat" "groundcontrol_assault" "groundcontrol_defence" "groundcontrol_territory" "groundcontrol_mission" "groundcontrol_raid" "groundcontrol_positions" "coop" "groundcontrol_duel" "battlezones_attack" "battlezones_attack_hq" "battlezones_defence" "battlezones_defence_hq" "battlezones_duel" "combat_duel" "groundcontrol_hold_lines" "battlezones_sectors" "battlezones_skirmish" "battlezones_armored" "combat_officer" "combat_attack" "combat_defence" "frontline_attack" "frontline_defence" "groundcontrol_manpower" "combat_manpower" "invasion_manpower" "combat_manpower" "invasion_manpower"}
	{priority 500}
	(include "hard.inc")	
}
