	{"vehicle"
		{colliderId "nothing"}
		{collideWith  "construction" "rock" "sandbag" "cannon" "cannon_small" "moto" "car" "truck" "armored" "tank.light" "tank.medium" "tank.heavy" "tree" "bush" "human" "particle" "particle.big" "trench"}
		{useRamVolume "cannon" "cannon_small" "moto" "car" "truck" "armored" "tank.light" "tank.medium" "tank.heavy"}
		{noContactWith "particle" "particle.big" "human" "bush" "stuff" "mine.at" "mine.ap" "flame" "trench"}
		{blocking
			{speed 10} ; kmph
			{penetration 0.2} ; m
		}
	}