(include "presets_vehicles.inc")
(include "presets_infantry.inc")
(include "presets_noart.inc")
;(include "presets_vehshort.inc")

;{presets
;		{"squad"		
;			{common
;				{unitset "squad|mortar|degtyarev_stan|mg34_stan|browning_stan^at_miners"}
;				;{commandPoints "infantry=21;cannon=2;stan=3;mortar=2;afv=1;tankx=1;tankl=1;tankm=1;tankh=1;spa=1;art=1"}
;				{chargeFactors "*=0"}
;				{budgets
;					{squad   {resource 10 32 0.3} {buttons "squad1 squad2"}}
;					{fixed   {resource 5 80 0.5} {buttons "vh_cn vh_cn1 lt ht asu"}}
;				} 
;			}
;		}
;}
